/**
 * Verify-fixture generator. `bun scripts/generate-verify-fixtures.ts`.
 * Signs a small fixed grid with the WORKING TREE and writes the (pub, sig, msg)
 * triples as literals to tests/corpus/verify-fixtures.ts, so the `verify`
 * corpus category is build-agnostic. Every signing input here is already a
 * golden vector proven against the reference; regenerating is a deliberate,
 * reviewed act.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as c from "../src/index.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const hex = (b: Uint8Array) => Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
const cyc = (n: number, start = 0) => Uint8Array.from({ length: n }, (_, i) => (start + i) & 0xff);
const PRIVS = [cyc(32, 1), cyc(32, 0x42), Uint8Array.from([...new Uint8Array(31), 1])];
const MSGS = [cyc(1, 7), cyc(32, 7)];
const AUX = cyc(32, 0x77);
const rows = [];
for (const priv of PRIVS)
  for (const msg of MSGS) {
    rows.push({
      scheme: "ecdsa",
      pub: hex(c.ecdsa.publicKey(priv)),
      sig: hex(c.ecdsa.sign(priv, msg)),
      msg: hex(msg),
    });
    rows.push({
      scheme: "schnorr",
      pub: hex(c.schnorr.publicKey(priv)),
      sig: hex(c.schnorr.sign(priv, msg, { auxRand: AUX })),
      msg: hex(msg),
    });
    rows.push({
      scheme: "ed25519",
      pub: hex(c.ed25519.publicKey(priv)),
      sig: hex(c.ed25519.sign(priv, msg)),
      msg: hex(msg),
    });
  }
const body = rows
  .map((r) => `  { scheme: "${r.scheme}", pub: "${r.pub}", sig: "${r.sig}", msg: "${r.msg}" },`)
  .join("\n");
writeFileSync(
  join(root, "tests/corpus/verify-fixtures.ts"),
  `/**
 * Signed triples for the \`verify\` corpus category.
 * GENERATED by scripts/generate-verify-fixtures.ts from the working tree;
 * the signing inputs (cycling-byte private keys 0x01…, 0x42…, the scalar 1;
 * messages cyc(1, 7) and cyc(32, 7); Schnorr aux-rand cyc(32, 0x77)) are
 * golden vectors already proven against the reference. FROZEN.
 */
export interface SignedTriple {
  scheme: "ecdsa" | "schnorr" | "ed25519";
  pub: string;
  sig: string;
  msg: string;
}
export const SIGNED: SignedTriple[] = [
${body}
];
`,
);
console.log(`wrote ${rows.length} triples`);
